app:
  port: 8000

mongo:
  uri: "mongodb://mongodb:27017"
  name: "testdb"
  user_collection: "users"
  bookmark_collection: "bookmarks"

auth:
  hash_salt: "randomhashsalt"
  signing_key: "supersecretkey"
  token_ttl: 86400