apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-api-app.fullname" . }}-config
data:
  PORT: "{{ .Values.app.port }}"
  MONGO_URI: "{{ .Values.mongo.uri }}"
  MONGO_NAME: "{{ .Values.mongo.name }}"
  MONGO_USER_COLLECTION: "{{ .Values.mongo.user_collection }}"
  MONGO_BOOKMARK_COLLECTION: "{{ .Values.mongo.bookmark_collection }}"
  AUTH_TOKEN_TTL: "{{ .Values.auth.token_ttl }}"
