apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-api-app.fullname" . }}
  labels:
    {{- include "go-api-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "go-api-app.selectorLabels" . | nindent 4 }}
